version: '2'

services:
  app:
    restart: always
    build: ./app
    expose:
      - "8101"
    volumes:
      - /usr/src/app/portal/static
    command: /usr/local/bin/gunicorn -w 2 -b :8101 app:app
    environment:
      DEBUG: 'False'
      SECRET_KEY: '123456'
    ports:
      - 8101:8101
