version: '2'

services:
  app:
    restart: always
    build: ./app
    env_file:
      - ./app.env
    command: /usr/local/bin/gunicorn -w 2 -b :8101 app:app
    environment:
      DEBUG: APP_FLASK_SECRET_KEY
      SECRET_KEY: APP_FLASK_DEBUG
    ports:
      - 8101:8101
